### PR TITLE
Add translation to Installation index page

### PR DESCRIPTION
**Pull request by ninh-nd**
This is my translation on the `Installation` index page. As this is my first time contributing to this project (and OSS in general), I have a few questions:
1. I'm still not certain about the translation of "sandbox" so I left it untouched. Any comment on this would be helpful.
2. Do I need to translate the parts that are not markdowns? (For example, the 'In this chapter' text that is rendered by a `.tsx`)

### CODE REVIEW

**Comment by ltmylinh** [comment]
> This is my translation on the `Installation` index page. As this is my first time contributing to this project (and OSS in general), I have a few questions:
> 
> 1. I'm still not certain about the translation of "sandbox" so I left it untouched. Any comment on this would be helpful.
> 2. Do I need to translate the parts that are not markdowns? (For example, the 'In this chapter' text that is rendered by a `.tsx`)

Thanks @ninh-nd. 
1. IMO with "sandbox" we can translate it into `ô bên dưới`, and I usually add the English next to the translation in case the Vietnamese words can be confused or hard to understand. For example, in this case, I will make `ô bên dưới (sandbox)` for it.
2. I think we can ignore the text in the component when we do translation for pages like this. And we can add a task to translate some texts in the components later. That's my thoughts. Someone might have a better idea.

**Comment by Ryan-LT** [comment]
Hi @ltmylinh and @ninh-nd,

1. Let's keep the `sandbox` as it is since [it's an actual platform](https://codesandbox.io/dashboard) to run code on the cloud.
2. Component texts should be kept. For most UI texts, the label will turn into confusion if we translate them. (eg: Button -> Nút Ấn). Those texts should be familiar to software engineers in general. I think we are trying to explain the **document** to people only.

**Comment by ltmylinh** [comment]
> Hi @ltmylinh and @ninh-nd,
> 
> 1. Let's keep the `sandbox` as it is since [it's an actual platform](https://codesandbox.io/dashboard) to run code on the cloud.
> 2. Component texts should be kept. For most UI texts, the label will turn into confusion if we translate them. (eg: Button -> Nút Ấn). Those texts should be familiar to software engineers in general. I think we are trying to explain the **document** to people only.

1. The `sandbox` here is a word, not the codesandbox - the platform that is being used to embed the code into the website. Btw, I respect people's thoughts so feel free to leave it as whatever ya'll think it's appropriate for Vietnamese people to learn tho 😊

**Comment by Ryan-LT** [comment]
Yeah. Exactly, I would keep mentioning that with "sandbox" because it's a direct reference to the codesanbox itself. Mentioning it using some other terms would lead to confusion, I can't find any proper name for it too. Looking forward to hearing your point.

**Pull request merged**
